### ISSUE TITLE
This ArchWSL is not compatible with WSL2

### ISSUE THREAD

**Issue by M87BlackHole** [yuk7/ArchWSL#89]
\rootfs is changed into a vhdx

**Comment by 12101111** [comment]
It works well for me.
Install as wsl1 and wsl --set-version arch 2
![图片](https://user-images.githubusercontent.com/8438475/59496304-b51f3900-8ec3-11e9-97fe-4a67f62ca28a.png)

**Comment by M87BlackHole** [comment]
Yes, I have done this, but it cannot work.

**Comment by lifanxi** [comment]
![image](https://user-images.githubusercontent.com/179042/61676077-41c3df00-ad2d-11e9-990a-f467077aec34.png)
I have the similar issue, cannot convert my existing WSL Arch Linux to WSL 2.

**Comment by arlllk** [comment]
I installed it two times (I broke the first one, that's on me).
But what I did is install it, after setting `wsl --set-default-version 2` , i and I was able to change to the default fakeroot, without any problems.

I never tried to install any other way, because I set the default version when it came out.
Maybe this way works.😅

**Comment by HoshiYamazaki** [comment]
![image](https://user-images.githubusercontent.com/21007545/61817590-26e98b80-ae4f-11e9-9eb9-9f00a2468071.png)

It works after second time? Not sure.

**Comment by arlllk** [comment]
The way I didt was 
1. `wsl --set-default-version 2`
2. Then install Arch

**Comment by HoshiYamazaki** [comment]
For me Arch is working fine.

Compile test of my hobby project:
make -j5  0.30s user 2.16s system 29% cpu 8.340 total //wsl1
make -j5  0.58s user 0.88s system 51% cpu 2.848 total //wsl2

**Comment by HoshiYamazaki** [comment]
```
ldconfig: File /usr/lib/libswrAVX.so.0.0.0 is empty, not checked.
ldconfig: File /usr/lib/librustc-c5b1587cca8ef79c.so is empty, not checked.
ldconfig: File /usr/lib/librustc_metadata-340eee917a2638d0.so is empty, not checked.
ldconfig: File /usr/lib/libEGL_mesa.so.0 is empty, not checked.
ldconfig: File /usr/lib/libglapi.so is empty, not checked.
ldconfig: File /usr/lib/libswrAVX.so.0 is empty, not checked.
ldconfig: File /usr/lib/librustc_errors-ee0f04cc5ea7be1d.so is empty, not checked.
ldconfig: File /usr/lib/libOSMesa.so is empty, not checked.
ldconfig: File /usr/lib/librustc_driver-313a9fde3f3ffdb3.so is empty, not checked.
ldconfig: File /usr/lib/libxatracker.so is empty, not checked.
ldconfig: File /usr/lib/libGLX_indirect.so.0 is empty, not checked.
ldconfig: File /usr/lib/librustc_incremental-95966278b65b0f1e.so is empty, not checked.
ldconfig: File /usr/lib/librustc_typeck-e2903780703cd2c8.so is empty, not checked.
ldconfig: File /usr/lib/libgbm.so.1 is empty, not checked.
ldconfig: File /usr/lib/librustc_interface-f532ff5e2c519508.so is empty, not checked.
ldconfig: File /usr/lib/librustc_mir-416e0ebe6034b16b.so is empty, not checked.
ldconfig: File /usr/lib/libGLX_mesa.so.0.0.0 is empty, not checked.
ldconfig: File /usr/lib/libEGL_mesa.so.0.0.0 is empty, not checked.
ldconfig: File /usr/lib/librustc_borrowck-637151f0e6538457.so is empty, not checked.
ldconfig: File /usr/lib/libsyntax_ext-f0d2026542f8e507.so is empty, not checked.
ldconfig: File /usr/lib/librustc_cratesio_shim-b164ef10f53c5aa1.so is empty, not checked.
ldconfig: File /usr/lib/librustc_target-22de2d30899b1c84.so is empty, not checked.
ldconfig: File /usr/lib/libOSMesa.so.8.0.0 is empty, not checked.
ldconfig: File /usr/lib/librustc_plugin-ecefaca193e6944b.so is empty, not checked.
ldconfig: File /usr/lib/libxatracker.so.2 is empty, not checked.
ldconfig: File /usr/lib/librustc_allocator-ac283b0735e349b2.so is empty, not checked.
ldconfig: File /usr/lib/libGLX_mesa.so is empty, not checked.
ldconfig: File /usr/lib/librustc_codegen_ssa-42ed48590f1cf042.so is empty, not checked.
ldconfig: File /usr/lib/libxatracker.so.2.5.0 is empty, not checked.
ldconfig: File /usr/lib/libsyntax_pos-9d13af6e78e337c4.so is empty, not checked.
ldconfig: File /usr/lib/librustc_traits-4207402e33a390db.so is empty, not checked.
ldconfig: File /usr/lib/libpkgconf.so.3 is empty, not checked.
ldconfig: File /usr/lib/librustc_privacy-4f5e75a96511f77a.so is empty, not checked.
ldconfig: File /usr/lib/libswrAVX2.so.0 is empty, not checked.
ldconfig: File /usr/lib/librustc_passes-4d5d572deb8cd310.so is empty, not checked.
ldconfig: File /usr/lib/libglapi.so.0.0.0 is empty, not checked.
ldconfig: File /usr/lib/libpkgconf.so.3.0.0 is empty, not checked.
ldconfig: File /usr/lib/librustc_codegen_utils-d1cdfed74738c364.so is empty, not checked.
ldconfig: File /usr/lib/librustc_lint-7f9e72d70536740e.so is empty, not checked.
ldconfig: File /usr/lib/libOSMesa.so.8 is empty, not checked.
ldconfig: File /usr/lib/libEGL_mesa.so is empty, not checked.
ldconfig: File /usr/lib/libswrAVX.so is empty, not checked.
ldconfig: File /usr/lib/libglapi.so.0 is empty, not checked.
ldconfig: File /usr/lib/libterm-15879d30d5614437.so is empty, not checked.
ldconfig: File /usr/lib/libarena-1049600338db0885.so is empty, not checked.
ldconfig: File /usr/lib/libserialize-53ef96713d73996f.so is empty, not checked.
ldconfig: File /usr/lib/libGLX_mesa.so.0 is empty, not checked.
ldconfig: File /usr/lib/librustc_fs_util-2df39053f6ecd7c7.so is empty, not checked.
ldconfig: File /usr/lib/libswrAVX2.so.0.0.0 is empty, not checked.
ldconfig: File /usr/lib/librustc_save_analysis-d9e5fb873491f4d5.so is empty, not checked.
ldconfig: File /usr/lib/libtest-13781f136b7f2a4f.so is empty, not checked.
ldconfig: File /usr/lib/libsyntax-2fa3e7aa31b9b9e3.so is empty, not checked.
ldconfig: File /usr/lib/libfmt_macros-18cb175548ae156b.so is empty, not checked.
ldconfig: File /usr/lib/libpkgconf.so is empty, not checked.
ldconfig: File /usr/lib/libgraphviz-e962f2e250c9810f.so is empty, not checked.
ldconfig: File /usr/lib/librustc_resolve-5015b1e238dbbdf9.so is empty, not checked.
ldconfig: File /usr/lib/libgbm.so.1.0.0 is empty, not checked.
ldconfig: File /usr/lib/librustc_macros-866b6c5bb932066b.so is empty, not checked.
ldconfig: File /usr/lib/libgbm.so is empty, not checked.
ldconfig: File /usr/lib/libswrAVX2.so is empty, not checked.
ldconfig: File /usr/lib/libstd-5e8d2eef5cf4a17a.so is empty, not checked.
ldconfig: File /usr/lib/librustc_data_structures-ea8e4ee585295ff9.so is empty, not checked.
```

I can't run compton, what the hell was done with container? I did anything other than rebooting an computer...

**Comment by HoshiYamazaki** [comment]
So, pretty much now whole container is broken and I can't even start zsh.
Use WSL2 with ArchWSL with caution:
![image](https://user-images.githubusercontent.com/21007545/61897497-71363f80-af17-11e9-97ef-b79fd9de0c8c.png)

**Comment by maeehart** [comment]
I did this too. For me the conversion finished OK, but after the conversion, I cannot start the container:
```
c:\Users\XXX\bin\Arch>Arch.exe
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

**Comment by garth** [comment]
I managed to get Arch running with WSL2 until the most recent windows build 18950. It works if you convert back to V1. Even on the windows store the number of available distros is now about 1/2 so I guess something has changed when they added localhost support.

**Comment by tinyzimmer** [comment]
For me it is working fine, however I did not do a conversion. Just set my default wsl version 2 and ran arch.exe.

However - and may require a separate issue? - I can't get GUI applications to launch. And that's following the instructions about using the Windows ip from /etc/resolv.conf for the `DISPLAY` and allowing public access on my x server. Is this something that was working on WSL1 for arch?

**Comment by zizzencs** [comment]
The new version of init in Windows build 18950 tries to create the /bin directory and fails with all distributions that link /usr/bin to /bin, including Arch. See: https://github.com/microsoft/WSL/issues/4371 - a fix is incoming.

**Comment by radu-matei** [comment]
I can also confirm that reverting to version 1 works, at least until a new Insiders build is out.
(Note: I don't work on the WSL team).

**Comment by GoncaloHit** [comment]
following this, is  it fixed yet ? i had to convert back to wsl 1

**Comment by radu-matei** [comment]
I just tried with 18956 and the issue is still present.

**Comment by zhscn** [comment]
after updating into 18956, arch broke out with WSL2

**Comment by lengthmin** [comment]
in 18956, Arch WSL2 is unable to start.

**Comment by Biswa96** [comment]
Guys, the issue is not in this distribution. See https://github.com/microsoft/WSL/issues/4371. Windows 10 insider build 18947 and above have this issue. Revert back to 18945 if possible. 

Generally when a issue is marked as "fixinbound" in WSL repo, it reaches to insider build between 4-5 weeks. So wait for next build...

**Comment by GoodbyeNJN** [comment]
Hello guys, [this solution](https://github.com/microsoft/WSL/issues/4371#issuecomment-521107556) works fine in 18963.

**Comment by Biswa96** [comment]
That is not a "solution", it's a workaround. If someone make any mistake during the operation the whole distribution may break. Also we should not break "the Arch way" 🤓

**Comment by Biswa96** [comment]
That is not a "solution", it's a workaround. If someone make any mistake during the operation the whole distribution may break. After all the issue is from WSL devs. Also we should not break "the Arch way" 🤓

**Comment by arlllk** [comment]
I find it better to wait for a build with wsl fixed, breaking WSL distros is horrible because you lose everything, the vhdx used by WSL2 is inaccessible AFAIK so, I will wait for a correct fix 😅

**Comment by zizzencs** [comment]
> Hello guys, [this solution](https://github.com/microsoft/WSL/issues/4371#issuecomment-521107556) works fine in 18963.

It solves the immediate problem of not being able to get to Arch in WSL2, but it breaks Arch in various ways. E.g. installing packages with yay sometimes just deletes the /usr/bin symlink and creates an empty directory instead. :-)

**Comment by dxhisboy** [comment]
> That is not a "solution", it's a workaround. If someone make any mistake during the operation the whole distribution may break. After all the issue is from WSL devs. Also we should not break "the Arch way"

It not only breaks the Arch way, but also makes the package "filesystem" cannot be upgraded.

**Comment by HoshiYamazaki** [comment]
![image](https://user-images.githubusercontent.com/21007545/63993370-7b3bf700-caf0-11e9-9e54-86e35b6fe2ae.png)

It's fixed now guys, take a care ;)

**Comment by HoshiYamazaki** [comment]
I was testing it by few mins and did an reboot and nothing broke, so I assume this is for 80% sure fixed.
Please somebody confirm that here too.

**Comment by arlllk** [comment]
To me was all ok too.

**Comment by XxblackicexX** [comment]
To me was all ok too.
win10 ver 18970.rs

**Comment by radu-matei** [comment]
I can confirm that this distro is working again in build 18980.1

**Comment by yuk7** [comment]
This is fixed in 18970.

**Comment by kridenberg** [comment]
There is still an error on the latest win10 build(
![зображення](https://user-images.githubusercontent.com/28910534/74036244-8ad73a00-49c4-11ea-9e56-61603a57050c.png)

**Comment by yuk7** [comment]
@kridenberg 
Please see:
https://github.com/microsoft/WSL/issues/4860#event-3010845934
